services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      DATABASE_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      REDIS_URL: redis://redis:6379/0
    entrypoint: ["sh", "-lc", "rm -f tmp/pids/server.pid && mkdir -p tmp/pids && exec \"$@\"", "--"]
    command: ["bin/rails", "server", "-b", "0.0.0.0", "-p", "3000"]

  db:
    image: postgres:17.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -h 127.0.0.1 -p 5432"]
      interval: 5s
      timeout: 5s
      retries: 20

  redis:
    image: redis:6.2
